# 等待世界名称（必须在配置文件中放入世界模板）
wait-world: "wait"
# 副本世界名称（必须在配置文件中放入世界模板）
war-world: "war"
# 人数达到多少人之后开始游戏
player: 2
# 完成匹配后倒计时多长时间开始游戏（单位：秒）
wait-time: 10
# 大厅位置（世界,x,y,z,yaw,pitch）
lobby-location: "world,0,100,0,0,0"
# 等待位置（x,y,z,yaw,pitch）
wait-location: "0,100,0,0,0"
# 出生位置
# 玩家随机在其中一个出生
# 注意：配置位置数量必须大于玩家人数
spawn-location:
  - "100,100,0,0,0"
  - "200,100,0,0,0"
  - "300,100,0,0,0"
# 副本世界创建完成后创建的npc
# (类型 名称 位置 指令)
spawn-npc:
  - 'PLAYER &a测试 0,100,0,0,0 say 1'
# 副本世界创建完成后创建的mob
# (类型 位置)
spawn-mob:
  - 'xx 0,100,0,0,0'
# 超时时间（单位：分钟）
timeout: 10
# 小队最大成员数量
team-max: 3

